"""add index unique

Revision ID: 9fc0ea4d0c23
Revises: 0e09985d5f24
Create Date: 2019-02-24 13:43:11.983951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc0ea4d0c23'
down_revision = '0e09985d5f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_url_shorten'), 'url', ['shorten'], unique=True)
    op.create_unique_constraint(None, 'url', ['origin'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    op.drop_index(op.f('ix_url_shorten'), table_name='url')
    # ### end Alembic commands ###
