"""add url table

Revision ID: d74bc26fe1a8
Revises: 
Create Date: 2019-02-23 19:43:06.147755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74bc26fe1a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('shorten', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_seq'), 'url', ['seq'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_seq'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
